/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary), 0.05)',
          100: 'rgb(var(--color-primary), 0.1)',
          200: 'rgb(var(--color-primary), 0.2)',
          300: 'rgb(var(--color-primary), 0.3)',
          400: 'rgb(var(--color-primary), 0.4)',
          500: 'rgb(var(--color-primary), 0.5)',
          600: 'rgb(var(--color-primary), 0.6)',
          700: 'rgb(var(--color-primary), 0.7)',
          800: 'rgb(var(--color-primary), 0.8)',
          900: 'rgb(var(--color-primary), 0.9)',
          950: 'rgb(var(--color-primary), 0.95)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary), 0.05)',
          100: 'rgb(var(--color-secondary), 0.1)',
          200: 'rgb(var(--color-secondary), 0.2)',
          300: 'rgb(var(--color-secondary), 0.3)',
          400: 'rgb(var(--color-secondary), 0.4)',
          500: 'rgb(var(--color-secondary), 0.5)',
          600: 'rgb(var(--color-secondary), 0.6)',
          700: 'rgb(var(--color-secondary), 0.7)',
          800: 'rgb(var(--color-secondary), 0.8)',
          900: 'rgb(var(--color-secondary), 0.9)',
          950: 'rgb(var(--color-secondary), 0.95)',
        },
        accent: {
          50: 'rgb(var(--color-accent), 0.05)',
          100: 'rgb(var(--color-accent), 0.1)',
          200: 'rgb(var(--color-accent), 0.2)',
          300: 'rgb(var(--color-accent), 0.3)',
          400: 'rgb(var(--color-accent), 0.4)',
          500: 'rgb(var(--color-accent), 0.5)',
          600: 'rgb(var(--color-accent), 0.6)',
          700: 'rgb(var(--color-accent), 0.7)',
          800: 'rgb(var(--color-accent), 0.8)',
          900: 'rgb(var(--color-accent), 0.9)',
          950: 'rgb(var(--color-accent), 0.95)',
        },
        success: {
          50: 'rgb(var(--color-success), 0.05)',
          100: 'rgb(var(--color-success), 0.1)',
          200: 'rgb(var(--color-success), 0.2)',
          300: 'rgb(var(--color-success), 0.3)',
          400: 'rgb(var(--color-success), 0.4)',
          500: 'rgb(var(--color-success), 0.5)',
          600: 'rgb(var(--color-success), 0.6)',
          700: 'rgb(var(--color-success), 0.7)',
          800: 'rgb(var(--color-success), 0.8)',
          900: 'rgb(var(--color-success), 0.9)',
          950: 'rgb(var(--color-success), 0.95)',
        },
        warning: {
          50: 'rgb(var(--color-warning), 0.05)',
          100: 'rgb(var(--color-warning), 0.1)',
          200: 'rgb(var(--color-warning), 0.2)',
          300: 'rgb(var(--color-warning), 0.3)',
          400: 'rgb(var(--color-warning), 0.4)',
          500: 'rgb(var(--color-warning), 0.5)',
          600: 'rgb(var(--color-warning), 0.6)',
          700: 'rgb(var(--color-warning), 0.7)',
          800: 'rgb(var(--color-warning), 0.8)',
          900: 'rgb(var(--color-warning), 0.9)',
          950: 'rgb(var(--color-warning), 0.95)',
        },
        error: {
          50: 'rgb(var(--color-error), 0.05)',
          100: 'rgb(var(--color-error), 0.1)',
          200: 'rgb(var(--color-error), 0.2)',
          300: 'rgb(var(--color-error), 0.3)',
          400: 'rgb(var(--color-error), 0.4)',
          500: 'rgb(var(--color-error), 0.5)',
          600: 'rgb(var(--color-error), 0.6)',
          700: 'rgb(var(--color-error), 0.7)',
          800: 'rgb(var(--color-error), 0.8)',
          900: 'rgb(var(--color-error), 0.9)',
          950: 'rgb(var(--color-error), 0.95)',
        },
      },
      spacing: {
        '8xl': '96rem',
        '9xl': '128rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      animation: {
        'gradient-x': 'gradient-x 8s ease infinite',
        'float': 'float 6s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      transitionTimingFunction: {
        'in-expo': 'cubic-bezier(0.95, 0.05, 0.795, 0.035)',
        'out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
      },
    },
  },
  plugins: [],
};